version: '3'
services:
  ros:
    build: .
    command: tail -f /dev/null
    #environment:
            #  - DISPLAY=novnc:0.0
    volumes:
      - ./workspace:/root/catkin_ws/
    env_file:
      - ros.env
    network_mode: "host"
